"""`accessmap export-site`: the static public site for Vercel (DECISIONS.md, Deployment).

site/
  index.html            frontend in static mode (<meta name="accessmap-mode" content="static">)
  stats.html            statistics page, same static mode
  data/*.json           config, barriers, network, stats, graph — same JSON as the local API
  router.js             in-browser router (port of accessmap.routing.router)
  photos/<frame>.jpg    frames used by barriers, resized (Mapillary, CC BY-SA 4.0)
  api/feedback.js       serverless feedback function (Neon Postgres), api/_ids.js
  package.json, vercel.json

Deploy with `npx vercel deploy site --prod`. The folder is build output (gitignored).
"""

from __future__ import annotations

import json
import logging
import shutil
from pathlib import Path

from accessmap.config import Settings
from accessmap.web.app import STATIC, SiteData

log = logging.getLogger(__name__)

VERCEL_TEMPLATE = Path(__file__).parent / "vercel"
MARKER = ".accessmap-site"
PHOTO_PX = 1024
PHOTO_QUALITY = 82
COORD_DIGITS = 6  # ~0.1 m


def _round(coords):
    if isinstance(coords[0], (int, float)):
        return [round(c, COORD_DIGITS) for c in coords]
    return [_round(c) for c in coords]


def slim_network(fc: dict) -> dict:
    """Geometry only: the UI draws the network, it does not read its tags."""
    return {"type": "FeatureCollection", "features": [
        {"type": "Feature", "properties": {},
         "geometry": {"type": f["geometry"]["type"],
                      "coordinates": _round(f["geometry"]["coordinates"])}}
        for f in fc["features"]]}


def _write_json(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, ensure_ascii=False, separators=(",", ":")),
                    encoding="utf-8", newline="\n")


def _prepare_out(out: Path) -> None:
    """Only ever clears a folder this exporter created (it carries MARKER)."""
    if out.exists() and any(out.iterdir()) and not (out / MARKER).is_file():
        raise FileExistsError(f"{out} exists and was not created by export-site; "
                              "choose another --out or remove it yourself")
    out.mkdir(parents=True, exist_ok=True)
    (out / MARKER).write_text("generated by accessmap export-site\n", encoding="utf-8")
    # Clear the contents but keep the folder and its marker: on Windows the folder itself
    # can be held open (e.g. by a local preview server), and a half-deleted folder
    # without its marker would lock out the next export.
    for child in out.iterdir():
        if child.name == MARKER:
            continue
        shutil.rmtree(child) if child.is_dir() else child.unlink()


def export_site(settings: Settings, out: Path) -> dict:
    from PIL import Image

    data = SiteData(settings)
    barriers = data.barriers()
    if not barriers:
        raise RuntimeError("no barriers: run `accessmap geolocate` first")
    _prepare_out(out)

    for page in ("index.html", "stats.html"):
        html = (STATIC / page).read_text(encoding="utf-8")
        html = html.replace("<head>", '<head>\n<meta name="accessmap-mode" content="static">', 1)
        (out / page).write_text(html, encoding="utf-8", newline="\n")

    # Feedback lives in the hosted DB online; the exported barriers carry none.
    _write_json(out / "data" / "config.json", data.config())
    _write_json(out / "data" / "barriers.json", {"type": "FeatureCollection",
                                                 "features": barriers})
    _write_json(out / "data" / "network.json", slim_network(data.network()))
    if data.graph() is not None:
        _write_json(out / "data" / "graph.json", data.graph())
        shutil.copy(STATIC / "router.js", out / "router.js")
    stats = data.stats()
    stats.pop("feedback")
    _write_json(out / "data" / "stats.json", stats)

    frames = data.frames()
    wanted = sorted({v["frame_id"] for f in barriers for v in f["properties"]["views"]})
    missing = []
    for fid in wanted:
        fr = frames.get(fid)
        src = settings.root / fr["path"] if fr else None
        if src is None or not src.is_file():
            missing.append(fid)
            continue
        with Image.open(src) as im:
            im = im.convert("RGB")
            im.thumbnail((PHOTO_PX, PHOTO_PX))
            (out / "photos").mkdir(exist_ok=True)
            im.save(out / "photos" / f"{fid}.jpg", "JPEG", quality=PHOTO_QUALITY,
                    optimize=True, progressive=True)
    if missing:
        log.warning("%d photos missing: %s", len(missing), missing[:5])

    shutil.copytree(VERCEL_TEMPLATE, out, dirs_exist_ok=True)
    ids = sorted(f["properties"]["id"] for f in barriers)
    (out / "api" / "_ids.js").write_text(
        "// Generated by accessmap export-site: barrier ids the feedback function accepts.\n"
        f"export const BARRIER_IDS = {json.dumps(ids)};\n", encoding="utf-8", newline="\n")

    size = sum(p.stat().st_size for p in out.rglob("*") if p.is_file())
    return {"out": str(out), "barriers": len(barriers), "photos": len(wanted) - len(missing),
            "photos_missing": len(missing), "size_mb": round(size / 1e6, 1)}
