"""`accessmap route-demo` (phase 6): 10 random pairs 400–1500 m apart, every active profile
→ reports/routing_demo.md + reports/qa/routing_demo.png."""

from __future__ import annotations

import math
import random
import time
from pathlib import Path

from accessmap.config import Settings
from accessmap.routing.graph import graph_path
from accessmap.routing.router import Router, RoutingError

SEED = 42
N_PAIRS = 10
MIN_M, MAX_M = 400.0, 1500.0
HEADER = ("| pair | profile | distance m | shortest m | problems on shortest | "
          "accessible m (detour) | problems on accessible | route | warnings |\n"
          "|---|---|---|---|---|---|---|---|---|\n")


def random_pairs(router: Router, n: int = N_PAIRS, seed: int = SEED) -> list[tuple]:
    """Pairs of graph node positions (so every point is on the network) 400–1500 m apart."""
    rnd = random.Random(seed)
    pairs = []
    while len(pairs) < n:
        a, b = rnd.sample(router.nodes, 2)
        d = math.hypot((a[0] - b[0]) * router.kx, (a[1] - b[1]) * 110_574.0)
        if MIN_M <= d <= MAX_M:
            pairs.append((a, b, d))
    return pairs


def _fmt_problems(p: dict) -> str:
    return ", ".join(f"{n} {t}" for t, n in sorted(p.items())) or "none"


def run(settings: Settings) -> dict:
    router = Router.from_file(graph_path(settings))
    pairs = random_pairs(router)
    rows, results, times = [], [], []
    for i, (a, b, d) in enumerate(pairs, 1):
        for prof in router.profiles:
            t0 = time.perf_counter()
            try:
                r = router.route(a, b, prof)
            except RoutingError as e:
                rows.append(f"| {i} | {prof} | {d:.0f} | error: {e} | | | | | |")
                continue
            times.append((time.perf_counter() - t0) * 1000)
            results.append((i, prof, r))
            warn = ", ".join(w["code"] for w in r["warnings"]) or ""
            rows.append(
                f"| {i} | {prof} | {d:.0f} | {r['baseline']['length_m']:.0f} | "
                f"{_fmt_problems(r['baseline']['problems'])} | {r['accessible']['length_m']:.0f} "
                f"({r['detour']:+.0%}) | {_fmt_problems(r['accessible']['problems'])} | "
                f"{'same' if r['same_route'] else 'different'} | {warn} |")

    differ = sum(not r["same_route"] for *_, r in results)
    stats = {"pairs": len(pairs), "routes": len(results), "differ": differ,
             "max_ms": round(max(times), 1), "median_ms": round(sorted(times)[len(times) // 2], 1),
             "warnings": sum(bool(r["warnings"]) for *_, r in results)}
    md = f"""# Routing demo

{N_PAIRS} random pairs of network points {MIN_M:.0f}–{MAX_M:.0f} m apart (straight line, seed
{SEED}), every active profile. Generated by `accessmap route-demo` from
`data/processed/routing_graph.json`. Barriers = detected (Gemini, prompt
{settings.project.gemini.prompt}) + OSM (`highway=steps`, `kerb=*`, `wheelchair=no`);
"problems" counts only barriers that matter for the profile (curb ramps are not problems).

- Routes: {stats['routes']}; accessible differs from shortest: **{differ}**; with warnings:
  {stats['warnings']}.
- Time per request (both routes): median {stats['median_ms']} ms, max {stats['max_ms']} ms.
- Max detour before a warning: +{router.max_detour:.0%}.

""" + HEADER + "\n".join(rows) + "\n\nMap: `reports/qa/routing_demo.png` (wheelchair).\n"
    out = settings.paths.reports / "routing_demo.md"
    out.write_text(md, encoding="utf-8", newline="\n")
    stats["report"] = str(out)
    stats["map"] = str(demo_map(settings, router, results))
    return stats


def demo_map(settings: Settings, router: Router, results: list) -> Path:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(11, 12), dpi=110)
    for e in router.edges:
        xs, ys = zip(*e["coords"], strict=True)
        ax.plot(xs, ys, color="#cccccc", lw=0.6, zorder=1)
    for b in router.barriers:
        if b["type"] in ("stairs", "step", "raised_curb", "rough_surface", "narrow_passage"):
            ax.scatter(*b["lonlat"], s=10, color="#b2182b" if b["type"] == "stairs" else "#8c510a",
                       zorder=2, linewidths=0)
    for i, prof, r in results:
        if prof != "wheelchair":
            continue
        bx, by = zip(*r["baseline"]["coords"], strict=True)
        ax.plot(bx, by, color="#e08214", lw=3.2, alpha=0.8, zorder=3)
        axx, ayy = zip(*r["accessible"]["coords"], strict=True)
        ax.plot(axx, ayy, color="#2166ac", lw=1.6, zorder=4,
                ls="-" if not r["warnings"] else "--")
        ax.annotate(str(i), r["baseline"]["coords"][0], fontsize=9, weight="bold", zorder=5)
    ax.plot([], [], color="#e08214", lw=3, label="shortest")
    ax.plot([], [], color="#2166ac", lw=1.6, label="accessible (wheelchair)")
    ax.plot([], [], color="#2166ac", lw=1.6, ls="--", label="accessible, with warning")
    ax.scatter([], [], s=10, color="#b2182b", label="stairs (OSM + detected)")
    ax.scatter([], [], s=10, color="#8c510a", label="other barriers")
    ax.legend(loc="upper left", fontsize=8)
    ax.set_aspect(1 / math.cos(math.radians(52.024)))
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_title("Routing demo: shortest vs accessible (wheelchair), numbers = pair start")
    path = settings.paths.qa / "routing_demo.png"
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return path
